spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3318/busmis?serverTimezone=GMT%2B8
    username: root
    password: root
    
mybatis:  mapper-locations:  - classpath*:/mappers/**/*.xml
  type-aliases-package:
    com.neusoft.busmis.security.model
  